language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - "pip install pep8"
  - "pip install coveralls"
  - "pip install -r requirements.txt"
script:
  ./tests.sh
after_success:
  coveralls
