site_name: dotdrop
site_url: https://github.com/deadc0de6/dotdrop
repo_url: https://github.com/deadc0de6/dotdrop
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
      - yaml
    collapse_navigation: false
use_directory_urls: true
nav:
  - Dotdrop: 'README.md'
  - Installation: 'installation.md'
  - 'Repository setup': 'repository-setup.md'
  - Usage: 'usage.md'
  - Config: 'config.md'
  - 'Config format': 'config-format.md'
  - 'Config details': 'config-details.md'
  - Templating: 'templating.md'
  - HowTo: 'howto/howto.md'
markdown_extensions:
  - meta
  - tables
  - fenced_code
  - toc:
      permalink: True
extra_css:
    - css/extra.css

