site_name: dotdrop
site_url: https://github.com/deadc0de6/dotdrop
repo_url: https://github.com/deadc0de6/dotdrop
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
      - yaml
    #collapse_navigation: false
use_directory_urls: true
nav:
  - 'Dotdrop': 'README.md'
  - 'Installation': 'installation.md'
  - 'Getting started': 'getting-started.md'
  - 'Usage': 'usage.md'
  - 'Config':
    - 'Config file': 'config/config-file.md'
    - 'Config block': 'config/config-config.md'
    - 'Dotfiles block': 'config/config-dotfiles.md'
    - 'Profiles block': 'config/config-profiles.md'
    - 'Actions block': 'config/config-actions.md'
    - 'Transformations block': 'config/config-transformations.md'
    - 'Variables block': 'config/config-variables.md'
    - 'Dynvariables block': 'config/config-dynvars.md'
    - 'Uservariables block': 'config/config-uservars.md'
  - 'Templating':
    - 'Templating': 'template/templating.md'
    - 'Template variables': 'template/template-variables.md'
    - 'Template methods': 'template/template-methods.md'
    - 'Template filters': 'template/template-filters.md'
    - 'Debugging templates': 'template/template-debug.md'
  - 'HowTo':
    - 'Append text to a dotfile on install': 'howto/append.md'
    - 'Create files on install': 'howto/create-special-files.md'
    - 'Group hosts and meta profiles': 'howto/group-hosts.md'
    - 'Handle compressed directories': 'howto/store-compressed-directories.md'
    - 'Handle secrets': 'howto/sensitive-dotfiles.md'
    - 'Handle special chars': 'howto/special-chars.md'
    - 'Improve Git integration': 'howto/improve-git-integration.md'
    - 'Include files or templates in templates': 'howto/include-in-template.md'
    - 'Manage system dotfiles': 'howto/system-config-files.md'
    - 'Merge files on install': 'howto/merge-files-when-installing.md'
    - 'Prompt user for variables': 'howto/prompt-user-for-variables.md'
    - 'Share content across dotfiles': 'howto/sharing-content.md'
    - 'Symlink dotfiles': 'howto/symlink-dotfiles.md'
    - 'Test latest dotdrop': 'howto/test-latest-dotdrop.md'
    - '': ''
    - '': ''
markdown_extensions:
  - meta
  - tables
  - fenced_code
  - toc:
      permalink: True
extra_css:
    - css/extra.css

